#!/usr/bin/env node
// Sync version from package.json → web/version.js
// Runs automatically before npm publish (prepublishOnly hook)

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
const version = pkg.version;

const content = `// Auto-generated by scripts/version-sync.mjs — do not edit manually
window.CLAWFEEL_VERSION = "${version}";
document.addEventListener('DOMContentLoaded', () => {
  const v = window.CLAWFEEL_VERSION;
  document.querySelectorAll('[data-version]').forEach(el => {
    el.textContent = el.textContent.replace(/v[\\\\d.]+/, 'v' + v);
  });
  document.querySelectorAll('[class*="footer"], footer').forEach(el => {
    if (el.innerHTML.match(/v\\\\d+\\\\.\\\\d+\\\\.\\\\d+/)) {
      el.innerHTML = el.innerHTML.replace(/v\\\\d+\\\\.\\\\d+\\\\.\\\\d+/, 'v' + v);
    }
  });
});
`;

writeFileSync(join(root, "web", "version.js"), content, "utf8");
console.log(`\u2705 version.js synced to v${version}`);
