// Auto-generated by scripts/version-sync.mjs — do not edit manually
window.CLAWFEEL_VERSION = "0.10.1";
document.addEventListener('DOMContentLoaded', () => {
  const v = window.CLAWFEEL_VERSION;
  document.querySelectorAll('[data-version]').forEach(el => {
    el.textContent = el.textContent.replace(/v[\\d.]+/, 'v' + v);
  });
  document.querySelectorAll('[class*="footer"], footer').forEach(el => {
    if (el.innerHTML.match(/v\\d+\\.\\d+\\.\\d+/)) {
      el.innerHTML = el.innerHTML.replace(/v\\d+\\.\\d+\\.\\d+/, 'v' + v);
    }
  });
});
